.gitignore
test/data/.gitignore
test/data/Project.toml
test/data/README.md
test/data/hepmc32summary.jl

Add script that summarises HepMC3 file content
Add more exclusions to .gitignore to prevent package getting bloated with auxiliary files

Add summary script and trim package content

---

README.md
examples/jetreco.jl
src/ClusterSequence.jl
src/GenericAlgo.jl
src/JetReconstruction.jl
test/runtests.jl

There is no need to have the prefix `generic` on the main interface, it's simpler just to call it `jet_reconstruct`.
Update the README to show how to run reconstruction using the "Best" strategy (this is the default way).
Add also a note on sorting (which is super trivial in Julia, so no need to support specific methods for
`Vector{PseudoJet}` as fastjet does).

Change generic method name to `jet_reconstruct`

---

README.md
src/JetVis.jl
src/Serialize.jl

This PR tackles the issue #43 by implementing an additional variant of the `jetsplot` function that works with `ClusterSequence` on top of the existing old one that has been developed in 2022 at the beginning of the project. Additionally, I have updated the serialisation methods, as they were partially deprecated and `savejets` was incompatible with the new things in the repository.

Fix plotting for `ClusterSequence` and update serialisation

---

.JuliaFormatter.toml
.github/workflows/Format.yml
examples/instrumented-jetreco.jl
examples/jetreco.jl
examples/parse-options.jl
examples/visualise-jets.jl
ext/JetVisualisation.jl
src/AlgorithmStrategyEnums.jl
src/ClusterSequence.jl
src/GenericAlgo.jl
src/HepMC3.jl
src/PlainAlgo.jl
src/Pseudojet.jl
src/Serialize.jl
src/TiledAlgoLL.jl
src/TiledAlgoLLStructs.jl
src/TiledAlgoUtils.jl
src/Utils.jl
test/data/hepmc32summary.jl
test/runtests.jl

Use code formatting with the setup:
```toml
style = "sciml"
yas_style_nesting = true
```
Source files are reformatted and a GitHub action is added

Code formatting

---

src/JetReconstruction.jl
src/Pseudojet.jl
src/Utils.jl
test/runtests.jl

This is a small cleanup for the `read_final_state_particles` function, allowing return type specialisation (avoiding the clunky need for two versions of the code).

Utils cleanup

---

examples/.gitignore
examples/visualise-jets-pluto.jl
ext/JetVisualisation.jl

Very minor updates to formatting and ignoring profiling outputs

Small fixes

---

docs/Project.toml
docs/make.jl
docs/package.json
docs/src/.vitepress/config.mts
docs/src/.vitepress/theme/index.ts
docs/src/.vitepress/theme/style.css
docs/src/index.md

the `.vitepress/` files are copied from https://github.com/LuxDL/DocumenterVitepress.jl/tree/master/template

use DocumenterVitepress.jl

---

Project.toml
src/ClusterSequence.jl
src/EEAlgorithm.jl
src/EEjet.jl
src/JetReconstruction.jl

Change the strategy for e+e- algorithms to hold all variables used in the repo calculations in a *structure of arrays*. This is achieved using a `struct` to hold the relevant variables per particle and the `StructArrays` package being used to generate the SoA structure from this for the reconstruction.
The speed-up is significant, approximately 40% of the original speed (this varies, based on the `R` parameter).
Significant refactoring of the implementation of the distance and metric distance calculation is done to use the new structures.

Optimise e+e- reconstruction

---

docs/make.jl
examples/instrumented-jetreco.jl
examples/jetreco.jl
src/ClusterSequence.jl
src/EEAlgorithm.jl
src/Utils.jl

When generalising `ClusterSequence` to also handle the `EEJet` type, the `jets` member was changed to be the *abstract* type `FourMomentum`.  This is type unstable and has a very negative impact on performance!
Fix `ClusterSequence` to be *parameterised*, where the type `T` is taken from the type of the jets passed in to the constructor.
This improves performance for $pp$ and $e^+e^-$ significantly.
Further fixes are to factorise out some of the `StructArray` handling functions in `EEAlgorithm.jl` to make the code logic easier to follow.

Fix significant performance regression

---

.github/dependabot.yml
.github/workflows/CI.yml

- Updated outdated actions used in CI workflow
- Added dependabot configuration to get updates for github actions: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates
This should silence annotation warnings about using deprecated version of Node in actions

Add dependabot configuration for CI and update CI actions

---

examples/instrumented-jetreco.jl
examples/jetreco.jl
examples/parse-options.jl
ext/JetVisualisation.jl
src/ClusterSequence.jl
src/GenericAlgo.jl
src/HepMC3.jl
src/PlainAlgo.jl
src/Pseudojet.jl
src/TiledAlgoLL.jl
src/TiledAlgoLLStructs.jl
src/TiledAlgoUtils.jl
src/Utils.jl
test/bootstrap_examples.jl
test/data/hepmc32summary.jl
test/runtests.jl
test/tests_examples.jl

Fixing a few typos in the docstrings and comments from sources, tests and examples

fix typos in comments and docstrings

---

docs/README.md
docs/src/examples.md
docs/src/index.md
examples/EDM4hep/SimpleRecoEDM4hep.jl
examples/README.md
examples/constituents/Project.toml
examples/constituents/README.md
examples/constituents/jetreco-constituents-nb.jl
examples/constituents/jetreco-constituents.jl
src/ClusterSequence.jl
src/JetReconstruction.jl
test/runtests.jl
test/test-constituents.jl

Formally added functions now to retrieve jet constituents - either as a list of indexes to the original particle collection, or as references to the reconstructed jet objects.
Documentation and examples are added.
Closes #68

Improved constituents

---

src/ClusterSequence.jl
src/JetReconstruction.jl
src/Substructure.jl
test/test-constituents.jl

Add `parent_jets()` accessor, that returns a jet's parents or nothing. Export this method.
~~"Promote" `has_parents` to ClusterSequence source file and ensure it works with both jet types (or any `FourMomentum`).~~ *Remove `has_parents` as unneeded*
Add tests for parent jet retrieval, in case where a jet has parents and also when it doesn't.
Closes #100

Add jet parents retrieval

---

.github/workflows/CFF.yml
CITATION.cff
README.md

Update the CITATION.cff file to reference our preferred citation.
Add the GitHub action to validate the CFF.
Add the CFF badge to the README.

Cff update

---

examples/test.sh
src/GenericAlgo.jl
test/runtests.jl
test/test-algpower-consistency.jl
test/test-compare-types.jl
test/test-jet_reconstruct-if.jl
test/test-jet_reconstruct-interface.jl

Fix the default value for `p` in `jet_reconstruct()` to be `nothing` (see #126).
Refactor the last tests run inside `runtests.jl` to be independent subtests.
Add a couple more example test cases 
Fixes #126 
Fixes #127

Fix default p value and refactor tests

---

src/EEjet.jl
src/TiledAlgoLLStructs.jl

This is very small. The docstring for `PseudoJet` includes `mutable` but docstings for other `mutable struct`s don't. I'm not sure whether including `mutable` is a recommended practice - I think I've seen packages both putting and avoiding it in the docs

add mutable keyword in mutable struct docstrings

---

README.md
src/AlgorithmStrategyEnums.jl
src/EEAlgorithm.jl
src/GenericAlgo.jl
src/PlainAlgo.jl
src/Substructure.jl
src/TiledAlgoLL.jl

Some of the docstings were missing `algorithm` argument or wrong type was given. There were some instances of power still documented as `Int`. `recluster` was using slightly inconsistent style of documentation
Also I try to smuggle here two non-docs change, I hope it's not very controversial: constrain strategy argument to be of enum type in `jet_reconstruct`, constrain algorithm in `recluster` to be enum type

Fix arguments in docstrings

---

docs/Project.toml
examples/EDM4hep/Project.toml
examples/Project.toml
examples/constituents/Project.toml
examples/substructure/Project.toml
examples/visualisation/Project.toml

One too many times I forgot to `dev` the main package and was running with package from JuliaHub and wondering where are my changes
I propose to use [`[sources]`](https://pkgdocs.julialang.org/v1.11/toml-files/#The-[sources]-section) directive so examples docs automatically pick-up local version of JetReconstruction.jl. It's still possible to `free` or `dev` somewhere else later.  This also shouldn't  interfere with CI.
The `[sources]` directive was added in Julia 1.11. For earlier versions this is transparent and not doing anything, so the package should still be `dev`ed manually. 
Probably in 1.12 some of these could be replaced with [`[workspace]`](https://pkgdocs.julialang.org/dev/toml-files/#The-[workspace]-section) to resolve all the dependencies for sub-projects together.

By default use local version of JetReconstruction in examples and docs

---

src/EEAlgorithm.jl
src/GenericAlgo.jl
src/PlainAlgo.jl
src/TiledAlgoLL.jl

Take an `AbstractVector` for the algorithm entry points instead of a `Vector`, allowing any vector-like collection to be used.
In particular this allows EDM4hep data to be used correctly again.
This PR targets the current 0.4 release branch.
Closes #147

Update input particles to be AbstractVector

---

src/ClusterSequence.jl
src/EEJet.jl
src/GenericAlgo.jl
src/PlainAlgo.jl
src/TiledAlgoLL.jl

I propose to add a short notice that the jets used as input for `jet_reconstruct` must have their cluster history indices properly set. I got confused by this in #172.
Should a similar notice appear also for `plain_jet_reconstruct`, `tiled_jet_reconstruct`, `ee_genkt_algorithm`?
Also fix some more minor typos I found on the way

Document requirements for input jets' history indices

---

examples/.gitignore
examples/instrumented-jetreco.jl
examples/jetreco.jl
examples/test.sh

The `--dump` option for `jetreco.jl` and `instrumented-jetreco.jl` was broken because either variable declaration was missing or type conversion was missing
Closes #181 
@mattleblanc

fix dump in jetreco and instrumented-jetreco examples

---

src/PlainAlgo.jl
src/TiledAlgoLL.jl

This a follow-up to #161. Some of the examples in docstrings were missing the `algorithm` argument

Fix missing algorithm arg in examples in docstrings

---

README.md
docs/src/softkiller.md
examples/EDM4hep/EDM4hepJets.jl
examples/EDM4hep/SimpleRecoEDM4hep.jl
examples/constituents/jetreco-constituents-nb.jl
examples/constituents/jetreco-constituents.jl
examples/instrumented-jetreco.jl
examples/jetreco.jl
examples/softkiller/softkiller_plots.jl
examples/softkiller/softkiller_runtime.jl
examples/substructure/jet-grooming.jl
examples/substructure/jet-tagging.jl
src/ClusterSequence.jl
src/CommonJetStructs.jl
src/EEAlgorithm.jl
src/PlainAlgo.jl
src/Substructure.jl
src/TiledAlgoLL.jl
src/Utils.jl
test/_common.jl
test/data/hepmc32summary.jl
test/test-compare-types.jl
test/test-constituents.jl
test/test-substructure.jl

As described in #185, passing a type as a keyword argument to a function causes a type instability. Passing type as a positional argument is fine. [reference](https://docs.julialang.org/en/v1/manual/methods/#Note-on-Optional-and-keyword-Arguments)
I propose here to change keyword argument `T=DefaultT` in `inclusive_jets`, `exclusive_jets`, etc. to be the last positional argument (and also constrain it to be `Type`), This eliminates the type instability but changes the interface. The last positional argument is a different convention that `Base.convert` and other standard functions but they don't allow the default value which we want to have
Another thing as pointed by @Moelf  is that parametric types used by in the default values (or used in examples) could be concretized.
Performance …

Fix type instability when passing type to a function, concretize default types

---

src/EEAlgorithm.jl
src/PlainAlgo.jl
src/TiledAlgoLL.jl

Prevent unnecessary copying of particle data for tiled jet reconstruction (this gains ~1% in runtime 😁).
Rename all internal reconstruction functions with a `!` as they mutate the particle data passed to them (it seeds the cluster sequence objects).
Make particles a positional argument for `_ee_genkt_algorithm!` to be consistent with pp versions.
Improve docstrings.
Fixes #192.

Internal function improvements

---

src/ClusterSequence.jl
src/Utils.jl
test/_common.jl
test/test-jet-utils.jl

Ensure the correct LorentzVectorCyl vector is returned from `exclusive_jets` and `inclusive_jets`.
Slightly relax tolerance for rapidity comparison, as some precision is lost in conversion back and forth.
This is the minimal fix for #197

Fix jet selector
